[server]
runOnSave = false
fileWatcherType = "none"
pythonPath = "python3.10"
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#0A7C86"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#262730"
font = "sans serif"
